/******************************************************************************
 *
 * File Name   : menu_engine.c
 *
 * Description :
 *
 *     Generic Menu Navigation Engine
 *
 *     This module implements the menu logic layer.
 *
 *     Responsibilities:
 *
 *         - Menu initialization
 *         - Navigation between items
 *         - Enter / Back handling
 *         - Callback execution
 *         - Current page management
 *
 *
 * Architecture:
 *
 *
 *          Buttons Layer
 *                |
 *                v
 *
 *          Menu Engine
 *
 *                |
 *        +-------+-------+
 *        |               |
 *        v               v
 *
 *    Menu Database     Renderer
 *
 *
 *
 * IMPORTANT:
 *
 *     This module does NOT know:
 *
 *         - LCD
 *         - GPIO
 *         - UART
 *         - ADC
 *
 *
 *     It only controls menu state.
 *
 *
 *
 * Project :
 *      Dual Voltage Monitor
 *
 * MCU :
 *      STM32F103C8T6
 *
 *
 * Author :
 *      Ali Modami
 *
 *
 * Version :
 *      1.1.0
 *
 ******************************************************************************/


/******************************************************************************
 *
 * Includes
 *
 ******************************************************************************/

#include "menu_engine.h"
#include "menu_items.h"

#include <stddef.h>
#include <stdint.h>



/******************************************************************************
 *
 * Private Variables
 *
 ******************************************************************************/

/*
 * Current active menu page.
 *
 * Renderer reads this page
 * to know what should be displayed.
 *
 */

static MenuPage_t *g_currentPage = NULL;



/*
 * Parent page.
 *
 * Used for BACK navigation.
 *
 * Current architecture supports
 * one level parent navigation.
 *
 */

static MenuPage_t *g_parentPage = NULL;



/*
 * Initialization flag.
 *
 */

static uint8_t g_menuEngineInitialized = 0;



/******************************************************************************
 *
 * Private Function Prototypes
 *
 ******************************************************************************/

static void MenuEngine_SelectNext(void);

static void MenuEngine_SelectPrevious(void);

static void MenuEngine_EnterItem(void);

static void MenuEngine_Back(void);



/******************************************************************************
 *
 * Public Function:
 *
 * MenuEngine_Init()
 *
 ******************************************************************************/

/**
 * @brief
 *      Initialize Menu Engine.
 *
 *
 * @details
 *
 *      This function connects the engine
 *      to the menu database.
 *
 *
 *      Required order:
 *
 *
 *          MenuItems_Init()
 *
 *                  |
 *                  v
 *
 *          MenuEngine_Init()
 *
 *
 */

void MenuEngine_Init(void)
{

    /*
     * Start from Main Menu.
     *
     * Main menu object is created
     * inside menu_items.c
     *
     */


    g_currentPage =
            &g_mainMenuPage;



    /*
     * Root menu has no parent.
     *
     */

    g_parentPage = NULL;



    /*
     * Engine is ready.
     *
     */

    g_menuEngineInitialized = 1;


}

/******************************************************************************
 *
 * MenuEngine_Process()
 *
 ******************************************************************************/

/**
 * @brief
 *      Process incoming menu event.
 *
 *
 * Events are generated by Button Application Layer.
 *
 * Engine does not know:
 *
 *      - GPIO
 *      - Button pins
 *      - HAL
 *
 *
 * It only receives logical events.
 *
 ******************************************************************************/

void MenuEngine_Process(MenuEvent_t event)
{

    /*
     * Safety check.
     *
     * Engine must be initialized before processing.
     *
     */

    if(g_menuEngineInitialized == 0)
    {
        return;
    }



    switch(event)
    {


        /*
         * Move selection upward.
         */

        case MENU_EVENT_UP:

            MenuEngine_SelectPrevious();

            break;



        /*
         * Move selection downward.
         */

        case MENU_EVENT_DOWN:

            MenuEngine_SelectNext();

            break;



        /*
         * Execute selected item.
         */

        case MENU_EVENT_ENTER:

            MenuEngine_EnterItem();

            break;



        /*
         * Return to parent page.
         */

        case MENU_EVENT_BACK:

            MenuEngine_Back();

            break;



        default:

            /*
             * Ignore unknown events.
             */

            break;

    }


}



/******************************************************************************
 *
 * MenuEngine_SelectNext()
 *
 ******************************************************************************/

/**
 * @brief
 *      Move selection to next menu item.
 *
 *
 * Navigation rule:
 *
 *      Item A
 *          |
 *          v
 *      Item B
 *          |
 *          v
 *      Item C
 *
 *
 * No circular navigation.
 *
 * Last item remains selected.
 *
 ******************************************************************************/

static void MenuEngine_SelectNext(void)
{

    MenuItem_t *currentItem;



    /*
     * Verify active page.
     */

    if(g_currentPage == NULL)
    {
        return;
    }



    /*
     * Get current selected item.
     */

    currentItem =
            g_currentPage->selectedItem;



    if(currentItem == NULL)
    {
        return;
    }



    /*
     * Check next item availability.
     */

    if(currentItem->next != NULL)
    {


        /*
         * Update selection pointer.
         */

        g_currentPage->selectedItem =
                currentItem->next;

    }


}



/******************************************************************************
 *
 * MenuEngine_SelectPrevious()
 *
 ******************************************************************************/

/**
 * @brief
 *      Move selection to previous menu item.
 *
 *
 * Navigation rule:
 *
 *      Item C
 *          |
 *          v
 *      Item B
 *          |
 *          v
 *      Item A
 *
 *
 * No wrap around.
 *
 ******************************************************************************/

static void MenuEngine_SelectPrevious(void)
{

    MenuItem_t *currentItem;



    /*
     * Verify active page.
     */

    if(g_currentPage == NULL)
    {
        return;
    }



    /*
     * Get current selection.
     */

    currentItem =
            g_currentPage->selectedItem;



    if(currentItem == NULL)
    {
        return;
    }



    /*
     * Check previous item.
     */

    if(currentItem->previous != NULL)
    {


        /*
         * Move selection backward.
         */

        g_currentPage->selectedItem =
                currentItem->previous;

    }


}



/******************************************************************************
 *
 * MenuEngine_GetSelectedItem()
 *
 ******************************************************************************/

/**
 * @brief
 *      Return current selected item.
 *
 *
 * Used by Renderer layer.
 *
 * Renderer only asks:
 *
 *      "Which item is selected?"
 *
 * It does not know navigation logic.
 *
 ******************************************************************************/

MenuItem_t *MenuEngine_GetSelectedItem(void)
{

    if(g_currentPage == NULL)
    {
        return NULL;
    }



    return g_currentPage->selectedItem;

}


/******************************************************************************
 *
 * MenuEngine_EnterItem()
 *
 ******************************************************************************/

/**
 * @brief
 *      Handle ENTER event.
 *
 *
 * This function checks the selected menu item
 * and performs the proper operation.
 *
 *
 * Supported item types:
 *
 *      MENU_ITEM_SUBMENU
 *
 *          Open child page
 *
 *
 *      MENU_ITEM_ACTION
 *
 *          Execute callback
 *
 *
 *      MENU_ITEM_VALUE
 *
 *          Reserved for settings engine
 *
 *
 ******************************************************************************/

static void MenuEngine_EnterItem(void)
{

    MenuItem_t *selectedItem;



    /*
     * Safety check:
     *
     * Engine must have
     * an active page.
     *
     */

    if(g_currentPage == NULL)
    {
        return;
    }



    /*
     * Get current selected item.
     *
     */

    selectedItem =
            g_currentPage->selectedItem;



    /*
     * No item selected.
     *
     */

    if(selectedItem == NULL)
    {
        return;
    }



    /*
     * Decide operation
     * based on item type.
     *
     */

    switch(selectedItem->type)
    {



        /**************************************************************
         *
         * Sub Menu Item
         *
         **************************************************************/

        case MENU_ITEM_SUBMENU:


            /*
             * Store current page.
             *
             * Required for BACK operation.
             *
             */

            g_parentPage =
                    g_currentPage;



            /*
             * Open child page.
             *
             */

            if(selectedItem->childPage != NULL)
            {

                g_currentPage =
                        selectedItem->childPage;


                /*
                 * After entering a new page,
                 * selection starts from first item.
                 *
                 */

                if(g_currentPage->firstItem != NULL)
                {

                    g_currentPage->selectedItem =
                            g_currentPage->firstItem;

                }

            }


            break;




        /**************************************************************
         *
         * Action Item
         *
         **************************************************************/

        case MENU_ITEM_ACTION:



            /*
             * Execute callback function.
             *
             * Callback belongs to menu item.
             *
             */

            if(selectedItem->enterCallback != NULL)
            {

                selectedItem->enterCallback(selectedItem);

            }


            break;




        /**************************************************************
         *
         * Value Item
         *
         **************************************************************/

        case MENU_ITEM_VALUE:


            /*
             * Value editing will be handled
             * by Settings module.
             *
             *
             * Examples:
             *
             *      Sample Time
             *
             *      Baud Rate
             *
             *      Alarm Limit
             *
             */


            break;




        default:


            /*
             * Unknown item type.
             *
             */

            break;


    }


}

/******************************************************************************
 *
 * MenuEngine_Back()
 *
 ******************************************************************************/

/**
 * @brief
 *      Return to previous menu page.
 *
 *
 * BACK operation:
 *
 *
 *      Main Menu
 *
 *          |
 *          |
 *          v
 *
 *      Settings Menu
 *
 *
 *          BACK
 *
 *
 *          |
 *          v
 *
 *      Main Menu
 *
 *
 *
 * The engine does not know anything about:
 *
 *      LCD
 *      Buttons
 *
 *
 * It only changes the active page pointer.
 *
 ******************************************************************************/

static void MenuEngine_Back(void)
{


    /*
     * Check if parent page exists.
     *
     *
     * If NULL:
     *
     *      We are already
     *      at root menu.
     *
     */

    if(g_parentPage == NULL)
    {
        return;
    }



    /*
     * Restore previous page.
     *
     */

    g_currentPage =
            g_parentPage;



    /*
     * Clear parent reference.
     *
     * Because current page
     * becomes active navigation level.
     *
     */

    g_parentPage =
            NULL;



    /*
     * Reset selection
     * to first item of restored page.
     *
     */

    if(g_currentPage->firstItem != NULL)
    {

        g_currentPage->selectedItem =
                g_currentPage->firstItem;

    }


}



/******************************************************************************
 *
 * MenuEngine_SetPage()
 *
 ******************************************************************************/

/**
 * @brief
 *      Force engine to open a specific page.
 *
 *
 * Used by:
 *
 *      - Application startup
 *      - Special screens
 *      - Service mode
 *      - Alarm pages
 *
 *
 * Note:
 *
 * This function does not execute callbacks.
 *
 * It only changes navigation state.
 *
 ******************************************************************************/

void MenuEngine_SetPage(MenuPage_t *page)
{

    if(page == NULL)
    {
        return;
    }



    /*
     * Change current page.
     *
     */

    g_currentPage =
            page;



    /*
     * Start from first item.
     *
     */

    if(g_currentPage->firstItem != NULL)
    {

        g_currentPage->selectedItem =
                g_currentPage->firstItem;

    }


}



/******************************************************************************
 *
 * MenuEngine_ResetSelection()
 *
 ******************************************************************************/

/**
 * @brief
 *      Move selection pointer
 *      to first item of current page.
 *
 *
 * Example:
 *
 *
 * Current:
 *
 *      Item 4
 *
 *
 * After reset:
 *
 *      Item 1
 *
 *
 ******************************************************************************/

void MenuEngine_ResetSelection(void)
{

    if(g_currentPage == NULL)
    {
        return;
    }



    /*
     * Select first item.
     *
     */

    g_currentPage->selectedItem =
            g_currentPage->firstItem;


}



/******************************************************************************
 *
 * End Of MenuEngine
 *
 ******************************************************************************/


/******************************************************************************
*
* MenuEngine_IsInitialized()
*
******************************************************************************/

/**
* @brief
*      Check menu engine initialization state.
*
*
* @return
*
*      1  : Engine initialized
*
*      0  : Engine not initialized
*
*
* This function is useful for:
*
*      - Debugging
*      - Application startup checks
*      - Safety conditions
*
******************************************************************************/

uint8_t MenuEngine_IsInitialized(void)
{

   return g_menuEngineInitialized;

}



/******************************************************************************
*
* MenuEngine_GetCurrentPage()
*
******************************************************************************/

/**
* @brief
*      Return current active page.
*
*
* Renderer uses this function
* to know what should be displayed.
*
*
* Menu Engine does not know:
*
*      LCD
*      Display size
*      Rendering method
*
*
* It only provides current state.
*
******************************************************************************/

MenuPage_t *MenuEngine_GetCurrentPage(void)
{

   return g_currentPage;

}



/******************************************************************************
*
* MenuEngine_GetSelectedItem()
*
******************************************************************************/

/**
* @brief
*      Return currently selected menu item.
*
*
* Renderer uses this pointer
* to draw selection indicator.
*
*
* Example:
*
*
*      > Live Monitor
*
*        Settings
*
*        System Info
*
*
******************************************************************************/




/******************************************************************************
*
* End Of File
*
******************************************************************************/
