/******************************************************************************
 * @file    menu_controller_adapter.c
 * @brief   Menu Controller Adapter Implementation
 *-----------------------------------------------------------------------------
 * Project :
 *      Dual Voltage Monitor
 *
 * Description :
 *
 *      This file implements the adapter layer between the
 *      button application module and the menu engine.
 *
 *
 *      The purpose of this layer is to prevent direct dependency
 *      between input hardware/application and menu navigation.
 *
 *
 *-----------------------------------------------------------------------------
 * Architecture:
 *
 *
 *          buttons.c
 *
 *              |
 *              v
 *
 *          button_app.c
 *
 *              |
 *              v
 *
 *  menu_controller_adapter.c
 *
 *              |
 *              v
 *
 *          menu_engine.c
 *
 *              |
 *              v
 *
 *       menu_renderer.c
 *
 *
 *-----------------------------------------------------------------------------
 * Responsibilities:
 *
 *      This module:
 *
 *          - Receives logical button commands.
 *          - Converts them into menu events.
 *          - Calls menu engine functions.
 *          - Maintains refresh information.
 *
 *
 *      This module DOES NOT:
 *
 *          - Read GPIO pins.
 *          - Debounce buttons.
 *          - Access LCD.
 *          - Store menu information.
 *
 *
 *-----------------------------------------------------------------------------
 * Design Reason:
 *
 *      Without this layer:
 *
 *          button_app.c
 *                 |
 *                 v
 *             menu_engine.c
 *
 *
 *      would create a strong dependency.
 *
 *
 *      With adapter:
 *
 *          button_app.c
 *
 *                 |
 *                 v
 *
 *       adapter layer
 *
 *                 |
 *                 v
 *
 *          menu_engine.c
 *
 *
 *      Each module has one responsibility.
 *
 *
 *-----------------------------------------------------------------------------
 * Author :
 *      Ali Modami
 *
 * Version :
 *      1.0.0
 *
 * Change History :
 *
 *      1.0.0
 *          Initial Plan A architecture version.
 *
 ******************************************************************************/



/******************************************************************************
 *                              Include Files
 ******************************************************************************/

#include "menu_controller_adapter.h"

#include "menu_engine.h"

#include <stddef.h>





/******************************************************************************
 *                         Private Variables
 ******************************************************************************/

/*
 * Last received command.
 *
 * Used mainly for:
 *
 *      - Debugging
 *      - Testing
 *
 */

static Button_AppCommand_t last_command =
        BUTTON_APP_CMD_NONE;





/*
 * Indicates that menu state has changed.
 *
 * When true:
 *
 *      Renderer should update LCD.
 *
 */

static bool refresh_required = false;





/******************************************************************************
 *                         Private Functions
 ******************************************************************************/

/**
 * @brief
 *      Convert button command into menu operation.
 *
 * @param command
 *
 *      Button application command.
 *
 * @details
 *
 *      This function contains the only mapping
 *      between button layer and menu layer.
 *
 */
static void MenuControllerAdapter_ExecuteCommand(
        Button_AppCommand_t command)
{

    switch(command)
    {

        case BUTTON_APP_CMD_UP:

            MenuEngine_MovePrevious();

            break;



        case BUTTON_APP_CMD_DOWN:

            MenuEngine_MoveNext();

            break;



        case BUTTON_APP_CMD_ENTER:

            MenuEngine_Enter();

            break;



        case BUTTON_APP_CMD_BACK:

            MenuEngine_Back();

            break;



        case BUTTON_APP_CMD_NONE:

        default:

            /*
             * No menu action.
             */

            break;

    }

}

/******************************************************************************
 *                         Public Functions
 ******************************************************************************/

/**
 * @brief
 *      Initialize menu controller adapter.
 *
 * @details
 *
 *      Clears internal state.
 *
 *      This function must be called during
 *      application startup before processing
 *      button commands.
 *
 */
void MenuControllerAdapter_Init(void)
{

    last_command =
            BUTTON_APP_CMD_NONE;



    refresh_required = false;

}





/**
 * @brief
 *      Process one button command.
 *
 * @param command
 *
 *      Command generated by button application layer.
 *
 * @details
 *
 *      Processing flow:
 *
 *
 *          button_app.c
 *
 *                |
 *                v
 *
 *          Adapter_Process()
 *
 *                |
 *                v
 *
 *          menu_engine.c
 *
 *
 */
void MenuControllerAdapter_Process(
        Button_AppCommand_t command)
{

    /*
     * Store command for debugging.
     */

    last_command = command;



    /*
     * Ignore empty command.
     */

    if(command == BUTTON_APP_CMD_NONE)
    {
        return;
    }



    /*
     * Execute menu operation.
     */

    MenuControllerAdapter_ExecuteCommand(
            command);



    /*
     * Menu engine internally changes
     * its state when navigation occurs.
     *
     * Request renderer refresh.
     */

    refresh_required = true;

}





/**
 * @brief
 *      Check refresh request.
 *
 * @return
 *
 *      true:
 *          LCD update required.
 *
 *      false:
 *          No update required.
 *
 */
bool MenuControllerAdapter_IsRefreshRequired(void)
{

    return refresh_required;

}





/**
 * @brief
 *      Clear refresh request.
 *
 * @details
 *
 *      Called after LCD renderer
 *      completes updating the display.
 *
 */
void MenuControllerAdapter_ClearRefreshRequest(void)
{

    refresh_required = false;

}





/**
 * @brief
 *      Get last processed command.
 *
 * @return
 *
 *      Last received button command.
 *
 */
Button_AppCommand_t MenuControllerAdapter_GetLastCommand(void)
{

    return last_command;

}





/******************************************************************************
 *                              End Of File
 ******************************************************************************/
