/******************************************************************************
 * @file    buttons.h
 * @brief   Professional Button Driver Public Interface
 *-----------------------------------------------------------------------------
 * Project :
 *      Dual Voltage Monitor
 *
 * Framework :
 *      Embedded Application Framework
 *
 * Description :
 *      This module provides a hardware-independent interface for managing
 *      push buttons.
 *
 *      The application never accesses GPIO directly.
 *
 *      Instead, this module:
 *
 *          • Reads hardware buttons
 *          • Performs software debounce
 *          • Detects Press
 *          • Detects Release
 *          • Detects Long Press
 *          • Detects Auto Repeat
 *          • Generates Button Events
 *
 *      This design completely separates hardware from application logic.
 *
 *-----------------------------------------------------------------------------
 * Design Rules
 *-----------------------------------------------------------------------------
 *
 *  1. Never access button GPIO outside this module.
 *
 *  2. All button processing is performed inside Buttons_Task().
 *
 *  3. Application receives Events only.
 *
 *  4. Driver implementation details remain private.
 *
 *  5. This module is completely reusable in future projects.
 *
 *-----------------------------------------------------------------------------
 * Author :
 *      Ali Modami & ChatGPT
 *
 * Version :
 *      1.0.0
 *
 * Created :
 *      2026-07-08
 *
 ******************************************************************************/

#ifndef BUTTONS_H
#define BUTTONS_H

#ifdef __cplusplus
extern "C"
{
#endif

/******************************************************************************
 *                              Include Files
 ******************************************************************************/

#include <stdbool.h>
#include <stdint.h>

/******************************************************************************
 *                              Button IDs
 ******************************************************************************/

/*
 * Logical identifiers for every button in the system.
 *
 * NOTE:
 * These IDs are independent from GPIO numbers.
 */

typedef enum
{
    BUTTON_ID_UP = 0,

    BUTTON_ID_DOWN,

    BUTTON_ID_ENTER,

    BUTTON_ID_BACK,

    BUTTON_ID_COUNT

} Button_Id_t;

/******************************************************************************
 *                              Button Events
 ******************************************************************************/

/*
 * Button events generated by the driver.
 *
 * The application only works with these events.
 *
 * Example:
 *
 *      Button = BUTTON_ID_UP
 *      Event  = BUTTON_EVENT_PRESS
 */

typedef enum
{
    BUTTON_EVENT_NONE = 0,

    /*
     * Button has been pressed.
     */

    BUTTON_EVENT_PRESS,

    /*
     * Button has been released.
     */

    BUTTON_EVENT_RELEASE,

    /*
     * Button has been held long enough
     * to generate a Long Press event.
     */

    BUTTON_EVENT_LONG_PRESS,

    /*
     * Button Auto Repeat event.
     */

    BUTTON_EVENT_REPEAT

} Button_EventType_t;

/******************************************************************************
 *                              Button Event
 ******************************************************************************/

/*
 * Complete event returned to the application.
 *
 * Example:
 *
 *      Button :
 *          BUTTON_ID_UP
 *
 *      Event :
 *          BUTTON_EVENT_PRESS
 */

typedef struct
{
    Button_Id_t button;

    Button_EventType_t event;

} Button_Event_t;

/******************************************************************************
 *                      Public Function Prototypes
 ******************************************************************************/

/**
 * @brief Initialize Button Driver.
 *
 * This function initializes all internal driver variables.
 *
 * GPIO configuration is NOT performed here.
 * GPIO must already be initialized by CubeMX.
 */
void Buttons_Init(void);

/**
 * @brief Periodic button processing task.
 *
 * This function shall be called continuously
 * from the main loop.
 *
 * It performs:
 *
 *      - GPIO reading
 *      - Debounce
 *      - State machine update
 *      - Event generation
 */
void Buttons_Task(void);

/**
 * @brief Get next available button event.
 *
 * @param event
 * Pointer to destination event structure.
 *
 * @return
 * true
 *      New event available.
 *
 * false
 *      No pending events.
 */
bool Buttons_GetEvent(Button_Event_t *event);

#ifdef __cplusplus
}
#endif

#endif /* BUTTONS_H */
