/******************************************************************************
 * @file    lcd_config.h
 * @brief   Character LCD hardware configuration
 *-----------------------------------------------------------------------------
 * Project :
 *      Dual Voltage Monitor
 *
 * Description :
 *      Hardware configuration layer for HD44780 compatible character LCD
 *      modules connected through PCF8574 I2C backpack.
 *
 *      Supported LCD modules:
 *
 *          - LCD 20x4
 *          - LCD 16x2
 *
 *      This file contains only hardware dependent settings.
 *      LCD driver logic remains independent from this configuration.
 *
 *-----------------------------------------------------------------------------
 * Hardware:
 *
 *      MCU:
 *          STM32F103C8T6
 *
 *      LCD Controller:
 *          HD44780 Compatible
 *
 *      I2C Expander:
 *          PCF8574 / PCF8574A
 *
 *-----------------------------------------------------------------------------
 * Design Rules:
 *
 *      1. Application modules must not access LCD hardware directly.
 *
 *      2. LCD hardware settings must exist only in this file.
 *
 *      3. Driver source code must remain reusable.
 *
 *      4. No magic numbers are allowed in driver implementation.
 *
 *-----------------------------------------------------------------------------
 * Author :
 *      Ali Modami
 *
 * Version :
 *      1.0.1
 *
 * Change History:
 *
 *      1.0.0
 *          Initial LCD configuration file.
 *
 *      1.0.1
 *          Fixed I2C handle visibility problem.
 *
 ******************************************************************************/


#ifndef LCD_CONFIG_H
#define LCD_CONFIG_H



#ifdef __cplusplus
extern "C"
{
#endif



/******************************************************************************
 *                              Include Files
 ******************************************************************************/

#include "main.h"

#include "stm32f1xx_hal_i2c.h"



/******************************************************************************
 *                              I2C Configuration
 ******************************************************************************/

/*
 * CubeMX generates the I2C handle.
 *
 * The real definition exists inside:
 *
 *      Core/Src/i2c.c
 *
 * Example:
 *
 *      I2C_HandleTypeDef hi2c1;
 *
 * Other modules need an external declaration to access it.
 */


/*
 * External I2C handle generated by CubeMX.
 */

extern I2C_HandleTypeDef hi2c1;



/*
 * LCD uses I2C1 peripheral.
 *
 * If another I2C peripheral is selected in the future,
 * only this macro should be changed.
 */

#define LCD_I2C_HANDLE             hi2c1



/******************************************************************************
 *                              LCD I2C Address
 ******************************************************************************/

/*
 * PCF8574 address range:
 *
 *      PCF8574:
 *          0x20 - 0x27
 *
 *      PCF8574A:
 *          0x38 - 0x3F
 *
 *
 * STM32 HAL requires 8-bit address.
 *
 * Conversion:
 *
 *      7-bit address << 1
 *
 *
 * Common LCD backpacks:
 *
 *      0x27  --> 0x4E
 *
 *      0x3F  --> 0x7E
 */


/*
 * Default LCD address.
 *
 * Most modules use 0x27.
 */

#define LCD_I2C_ADDRESS            (0x4E)



/*
 * Alternative address:
 *
 * If LCD scanner detects 0x3F:
 *
 * Comment the definition above and enable:
 *
 * #define LCD_I2C_ADDRESS         (0x7E)
 *
 */



/******************************************************************************
 *                              LCD Geometry
 ******************************************************************************/

/*
 * Current hardware:
 *
 *      LCD 20x4
 */


#define LCD_COLUMNS                20U

#define LCD_ROWS                   4U



/*
 * LCD 16x2 configuration:
 *
 * To use LCD 16x2:
 *
 * Comment the two definitions above.
 *
 * Enable:
 *
 * #define LCD_COLUMNS             16U
 *
 * #define LCD_ROWS                 2U
 *
 */



/******************************************************************************
 *                              LCD Timing
 ******************************************************************************/

/*
 * Required delays for HD44780 controller.
 *
 * Values are centralized here to prevent magic numbers.
 */


#define LCD_ENABLE_PULSE_DELAY_MS  1U


#define LCD_COMMAND_DELAY_MS       2U


#define LCD_CLEAR_DELAY_MS         5U



/******************************************************************************
 *                              LCD Features
 ******************************************************************************/

/*
 * Default LCD features.
 */


#define LCD_BACKLIGHT_ENABLE       1U


#define LCD_CURSOR_ENABLE          0U


#define LCD_CURSOR_BLINK_ENABLE    0U



#ifdef __cplusplus
}
#endif



#endif /* LCD_CONFIG_H */
