/******************************************************************************
 * @file    menu_controller_adapter.h
 * @brief   Menu Controller Adapter Public Interface
 *-----------------------------------------------------------------------------
 * Project :
 *      Dual Voltage Monitor
 *
 * Description :
 *
 *      This file defines the public interface of the menu controller adapter.
 *
 *
 *      The purpose of this layer is to isolate the menu engine from the
 *      input source.
 *
 *
 *      The menu engine should not know:
 *
 *          - Which button hardware exists.
 *          - How buttons are debounced.
 *          - How button events are generated.
 *
 *
 *      Instead, this adapter converts application level button commands
 *      into menu navigation requests.
 *
 *
 *-----------------------------------------------------------------------------
 * Architecture:
 *
 *
 *              Physical Buttons
 *
 *                    |
 *                    v
 *
 *              buttons.c
 *
 *                    |
 *                    v
 *
 *              button_app.c
 *
 *                    |
 *                    v
 *
 *       menu_controller_adapter.c
 *
 *                    |
 *                    v
 *
 *              menu_engine.c
 *
 *                    |
 *                    v
 *
 *            menu_renderer.c
 *
 *
 *-----------------------------------------------------------------------------
 * Responsibilities:
 *
 *      This module:
 *
 *          - Receives Button_AppCommand_t commands.
 *          - Translates commands into menu operations.
 *          - Keeps input layer separated from menu engine.
 *          - Provides future expansion point.
 *
 *
 *      This module DOES NOT:
 *
 *          - Read GPIO.
 *          - Control LCD.
 *          - Store menu data.
 *          - Execute application actions.
 *
 *
 *-----------------------------------------------------------------------------
 * Design Goals:
 *
 *      1. Hardware independence.
 *
 *          Future input devices can replace buttons:
 *
 *              - Rotary encoder
 *              - Touch buttons
 *              - Remote control
 *
 *
 *      2. Clean software layers.
 *
 *
 *      3. Easier testing.
 *
 *          Menu engine can be tested without real hardware.
 *
 *
 *-----------------------------------------------------------------------------
 * Example:
 *
 *
 *      User presses DOWN button
 *
 *              |
 *              v
 *
 *      Button driver detects press
 *
 *              |
 *              v
 *
 *      Button application generates:
 *
 *              BUTTON_APP_CMD_DOWN
 *
 *              |
 *              v
 *
 *      MenuControllerAdapter_Process()
 *
 *              |
 *              v
 *
 *      MenuEngine_MoveNext()
 *
 *
 *-----------------------------------------------------------------------------
 * Author :
 *      Ali Modami
 *
 * Version :
 *      1.0.0
 *
 * Change History :
 *
 *      1.0.0
 *          Initial Plan A architecture version.
 *
 ******************************************************************************/



#ifndef MENU_CONTROLLER_ADAPTER_H
#define MENU_CONTROLLER_ADAPTER_H



#ifdef __cplusplus
extern "C"
{
#endif



/******************************************************************************
 *                              Include Files
 ******************************************************************************/

#include <stdint.h>

#include "button_app.h"





/******************************************************************************
 *                         Public Functions
 ******************************************************************************/

/**
 * @brief
 *      Initialize menu controller adapter.
 *
 * @details
 *
 *      Initializes internal adapter state.
 *
 *      Must be called before using:
 *
 *          MenuControllerAdapter_Process()
 *
 */
void MenuControllerAdapter_Init(void);





/**
 * @brief
 *      Process one button command.
 *
 * @details
 *
 *      This function is called periodically
 *      from the main application loop.
 *
 *
 *      It receives commands generated by
 *      button_app layer and forwards them
 *      to menu engine.
 *
 *
 * @param command
 *
 *      Button application command.
 *
 */
void MenuControllerAdapter_Process(
        Button_AppCommand_t command);


/******************************************************************************
 *                         Public Functions (continued)
 ******************************************************************************/

/**
 * @brief
 *      Check whether menu update is required.
 *
 * @details
 *
 *      Some commands may change menu state.
 *
 *      This flag informs the application layer
 *      that LCD renderer should refresh.
 *
 *
 * @return
 *
 *      true:
 *          Menu display changed.
 *
 *      false:
 *          No update required.
 *
 */
bool MenuControllerAdapter_IsRefreshRequired(void);





/**
 * @brief
 *      Clear refresh request flag.
 *
 * @details
 *
 *      Called after renderer updates LCD.
 *
 */
void MenuControllerAdapter_ClearRefreshRequest(void);





/**
 * @brief
 *      Get last processed command.
 *
 * @details
 *
 *      Useful for debugging and testing.
 *
 *
 * @return
 *
 *      Last received button command.
 *
 */
Button_AppCommand_t MenuControllerAdapter_GetLastCommand(void);





/******************************************************************************
 *                              End Of File
 ******************************************************************************/

#ifdef __cplusplus
}
#endif



#endif /* MENU_CONTROLLER_ADAPTER_H */
