/******************************************************************************
 *
 * @file    menu_engine.h
 *
 * @brief   Runtime Menu Navigation Engine Interface
 *
 *------------------------------------------------------------------------------
 *
 * Project:
 *
 *      Dual Voltage Monitor
 *
 *------------------------------------------------------------------------------
 *
 * MCU:
 *
 *      STM32F103C8T6
 *
 *------------------------------------------------------------------------------
 *
 * Framework:
 *
 *      STM32 HAL
 *
 *------------------------------------------------------------------------------
 *
 * Description:
 *
 *      This file defines the public interface of the menu runtime engine.
 *
 *      The menu engine is responsible for:
 *
 *          - Runtime navigation
 *          - Item selection
 *          - Page switching
 *          - Event processing
 *          - Edit mode handling
 *          - Renderer synchronization flags
 *
 *
 *      The menu engine does NOT:
 *
 *          - Control LCD hardware
 *          - Read buttons directly
 *          - Store application settings
 *          - Render graphics
 *
 *
 * Architecture:
 *
 *
 *              Button Driver
 *                    |
 *                    v
 *
 *              Menu Events
 *                    |
 *                    v
 *
 *             menu_engine.c
 *                    |
 *          +---------+---------+
 *          |                   |
 *          v                   v
 *
 *    menu_items.c       menu_renderer.c
 *
 *
 *------------------------------------------------------------------------------
 *
 * Dependencies:
 *
 *      menu_types.h
 *
 *------------------------------------------------------------------------------
 *
 * Author:
 *
 *      Ali Modami
 *
 *------------------------------------------------------------------------------
 *
 * Version:
 *
 *      2.1.0
 *
 ******************************************************************************/


#ifndef MENU_ENGINE_H
#define MENU_ENGINE_H



/******************************************************************************
 * Includes
 ******************************************************************************/

#include "menu_types.h"



#ifdef __cplusplus
extern "C"
{
#endif




/******************************************************************************
 * Initialization
 ******************************************************************************/

/**
 * @brief
 *      Initializes menu engine.
 *
 * @details
 *
 *      Initialization sequence:
 *
 *          1. Initialize static menu database.
 *
 *          2. Reset runtime state.
 *
 */
void MenuEngine_Init(void);





/**
 * @brief
 *      Resets runtime engine state.
 *
 * @details
 *
 *      Returns engine to root menu page.
 *
 */
void MenuEngine_Reset(void);





/**
 * @brief
 *      Releases menu engine resources.
 *
 * @details
 *
 *      Static allocation is used.
 *      This function only clears runtime state.
 *
 */
void MenuEngine_DeInit(void);





/******************************************************************************
 * Runtime Access
 ******************************************************************************/

/**
 * @brief
 *      Returns internal engine object.
 *
 * @return
 *      Pointer to runtime engine instance.
 *
 */
MenuEngine_t *MenuEngine_GetInstance(void);





/**
 * @brief
 *      Returns active menu page.
 *
 */
MenuPage_t *MenuEngine_GetCurrentPage(void);





/**
 * @brief
 *      Returns selected menu item.
 *
 */
MenuItem_t *MenuEngine_GetSelectedItem(void);





/******************************************************************************
 * Navigation Control
 ******************************************************************************/

/**
 * @brief
 *      Moves selection upward.
 *
 */
void MenuEngine_MoveUp(void);





/**
 * @brief
 *      Moves selection downward.
 *
 */
void MenuEngine_MoveDown(void);





/**
 * @brief
 *      Executes current selected item.
 *
 */
void MenuEngine_ExecuteSelectedItem(void);





/**
 * @brief
 *      Returns to previous page.
 *
 */
void MenuEngine_Back(void);





/******************************************************************************
 * Event Processing
 ******************************************************************************/

/**
 * @brief
 *      Processes menu input event.
 *
 * @param event
 *      Menu event generated by input layer.
 *
 */
void MenuEngine_ProcessEvent(
        MenuEvent_t event);





/******************************************************************************
 * Edit Mode
 ******************************************************************************/

/**
 * @brief
 *      Returns edit mode status.
 *
 * @return
 *      true:
 *          Engine currently editing.
 *
 */
bool MenuEngine_IsEditMode(void);



/**
 * @brief
 *      Enables or disables edit mode.
 *
 */
void MenuEngine_SetEditMode(
        bool enable);



/******************************************************************************
 * Engine State Management
 ******************************************************************************/

/**
 * @brief
 *      Returns current engine state.
 *
 * @return
 *      Current MenuState_t value.
 *
 */
MenuState_t MenuEngine_GetState(void);





/**
 * @brief
 *      Changes current engine state.
 *
 * @param state
 *      New runtime state.
 *
 */
void MenuEngine_SetState(
        MenuState_t state);





/******************************************************************************
 * Refresh Synchronization
 *
 * These functions provide communication between:
 *
 *          Menu Engine
 *                |
 *                v
 *          Menu Renderer
 *
 * The engine only reports that something changed.
 *
 * Rendering decisions remain outside this module.
 *
 ******************************************************************************/

/**
 * @brief
 *      Requests complete page refresh.
 *
 * @details
 *
 *      Used after:
 *
 *          - Page change
 *          - Entering edit mode
 *          - Leaving edit mode
 *
 */
void MenuEngine_RequestPageRefresh(void);





/**
 * @brief
 *      Requests selection refresh.
 *
 * @details
 *
 *      Used when only cursor position changes.
 *
 */
void MenuEngine_RequestSelectionRefresh(void);





/**
 * @brief
 *      Requests complete menu refresh.
 *
 * @details
 *
 *      Activates both:
 *
 *          - Page refresh flag
 *          - Selection refresh flag
 *
 */
void MenuEngine_RequestFullRefresh(void);





/**
 * @brief
 *      Requests cursor-only refresh.
 *
 */
void MenuEngine_RequestCursorRefresh(void);





/**
 * @brief
 *      Checks page refresh request.
 *
 * @return
 *
 *      true:
 *          Page update required.
 *
 */
bool MenuEngine_IsPageChanged(void);





/**
 * @brief
 *      Clears page refresh flag.
 *
 */
void MenuEngine_ClearPageChanged(void);





/**
 * @brief
 *      Checks selection refresh request.
 *
 * @return
 *
 *      true:
 *          Cursor update required.
 *
 */
bool MenuEngine_IsSelectionChanged(void);





/**
 * @brief
 *      Clears selection refresh flag.
 *
 */
void MenuEngine_ClearSelectionChanged(void);





/******************************************************************************
 * Information Access
 ******************************************************************************/

/**
 * @brief
 *      Returns number of items in current page.
 *
 */
uint8_t MenuEngine_GetItemCount(void);





/**
 * @brief
 *      Checks if current page is root.
 *
 */
bool MenuEngine_IsRootPage(void);





/**
 * @brief
 *      Returns current page identifier.
 *
 */
uint16_t MenuEngine_GetCurrentPageId(void);





/**
 * @brief
 *      Returns current item identifier.
 *
 */
uint16_t MenuEngine_GetCurrentItemId(void);






/******************************************************************************
 * Runtime Synchronization And Service
 ******************************************************************************/

/**
 * @brief
 *      Synchronizes engine state with menu database.
 *
 * @details
 *
 *      This function validates runtime references and
 *      restores invalid selections.
 *
 *      Mainly intended for:
 *
 *          - Debug support
 *          - Runtime recovery
 *          - Service functions
 *
 */
void MenuEngine_DebugRefresh(void);





/**
 * @brief
 *      Executes periodic engine service.
 *
 * @details
 *
 *      Reserved for future extensions:
 *
 *          - Long key processing
 *          - Timeout handling
 *          - Automatic page return
 *          - Message timeout
 *
 *      Call from main application loop.
 *
 */
void MenuEngine_Update(void);





/**
 * @brief
 *      Executes internal runtime synchronization.
 *
 * @details
 *
 *      Normal application code should use:
 *
 *          MenuEngine_Service()
 *
 *      instead of directly accessing internal
 *      synchronization functions.
 *
 */
void MenuEngine_Service(void);





/**
 * @brief
 *      Synchronizes current selection with active page.
 *
 * @details
 *
 *      Ensures:
 *
 *          currentItem
 *              =
 *          currentPage->selectedItem
 *
 */
void MenuEngine_SynchronizeSelection(void);





/**
 * @brief
 *      Resets current page selection.
 *
 * @details
 *
 *      Moves selection cursor to first item.
 *
 */
void MenuEngine_ResetCurrentPageSelection(void);





/******************************************************************************
 * Runtime Validation
 ******************************************************************************/

/**
 * @brief
 *      Checks if active page exists.
 *
 * @return
 *
 *      true:
 *          Current page is valid.
 *
 */
bool MenuEngine_HasCurrentPage(void);





/**
 * @brief
 *      Checks if selected item exists.
 *
 * @return
 *
 *      true:
 *          Selected item is valid.
 *
 */
bool MenuEngine_HasSelectedItem(void);





/**
 * @brief
 *      Checks if menu navigation is enabled.
 *
 * @return
 *
 *      true:
 *          UP/DOWN navigation allowed.
 *
 *      false:
 *          Engine is editing.
 *
 */
bool MenuEngine_IsNavigationEnabled(void);





/**
 * @brief
 *      Validates complete runtime state.
 *
 * @return
 *
 *      true:
 *          Runtime objects are valid.
 *
 */
bool MenuEngine_IsValid(void);





/******************************************************************************
 * Debug Information
 ******************************************************************************/

/**
 * @brief
 *      Returns textual representation of engine state.
 *
 * @return
 *      Constant string.
 *
 * Example:
 *
 *      "IDLE"
 *      "EDIT"
 *
 */
const char *MenuEngine_GetStateName(void);






/******************************************************************************
 * Internal Design Notes
 ******************************************************************************/

/*

Menu Engine Ownership Model:


        +--------------------------------+
        |        Menu Database           |
        |                                |
        | menu_items.c                   |
        |                                |
        | MenuPage_t                     |
        | MenuItem_t                     |
        +---------------+----------------+
                        |
                        |
                        v


        +--------------------------------+
        |        Menu Engine             |
        |                                |
        | menu_engine.c                  |
        |                                |
        | Runtime State                  |
        | Navigation                     |
        | Selection                      |
        | Edit Management                |
        +---------------+----------------+
                        |
                        |
                        v


        +--------------------------------+
        |        Menu Renderer           |
        |                                |
        | LCD Presentation               |
        | Cursor Display                 |
        +--------------------------------+



Rules:


1.
Menu Engine never accesses LCD hardware.


2.
Menu Engine never reads buttons directly.


3.
Menu Engine does not own application values.


4.
Menu Database contains static menu objects.


5.
Application modules communicate through callbacks.


6.
Renderer only observes engine state
and refresh flags.



*/





/******************************************************************************
 * Version Information
 ******************************************************************************/

/**
 * @brief
 *      Menu Engine Header Version.
 *
 */
#define MENU_ENGINE_VERSION_MAJOR      (2U)

#define MENU_ENGINE_VERSION_MINOR      (1U)

#define MENU_ENGINE_VERSION_PATCH      (0U)



#define MENU_ENGINE_VERSION_STRING     "2.1.0"





/******************************************************************************
 * C++ Compatibility
 ******************************************************************************/

#ifdef __cplusplus
}
#endif



#endif /* MENU_ENGINE_H */



/******************************************************************************
 *
 * Revision History
 *
 ******************************************************************************

Version 2.1.0

Date:
2026-07-16


Changes:


    - Rewritten according to menu_engine.c version 2.1.0.


    - Removed dependency on LCD modules.


    - Added runtime synchronization API.


    - Added refresh communication interface.


    - Unified edit mode interface.


    - Added validation and debug functions.


    - Preserved static allocation architecture.



******************************************************************************/


